console: false
concurrent: 10
ali-table-store:
  endPoint: "https://mark-sence-tool.cn-beijing.ots.aliyuncs.com"
  accessKeyId: ""
  accessKeySecret: ""
  instanceName: "mark-sence-tool"
  imageTableName: "project_images"
  labelTableName: "image_labels"
  projectTableName: "projects"
  projectId: "37fd5efa-f438-4f20-93f5-4fdd846f5106"
alibucket:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucketName:
  style: imageTool/resize,w_1024
  imageWidth: 1024
  imageHeight: 1024
dataset:
  labelSql: ""
  classSql: ""
  splitImageOutPath: split
  # 标签框缩放 zoomRect/100=结果/原始大小
  zoomRect: 100
  # 新的索引值映射关系
  classMap:
    - oldIndex: "1"
      newIndex: "0"
      oldName: lianpu-hualian-ping
      newName: lianpu-hualian-ping

    - oldIndex: "2"
      newIndex: "1"
      oldName: lianpu-huadan-ping
      newName: lianpu-huadan-ping