console: false
concurrent: 10
mysql:
  username: "root"
  password: "123"
  network: tcp
  server: 127.0.0.1
  port: 3306
  database: mark
alibucket:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucketName:
  style: imageTool/resize,w_1024
  imageWidth: 1024
  imageHeight: 1024
dataset:
  labelSql: ""
  classSql: ""
  splitImageOutPath: split
  # 标签框缩放 zoomRect/100=结果/原始大小
  zoomRect: 100
  # 新的索引值映射关系
  classMap:
    - oldIndex: "1"
      newIndex: "0"
      oldName: lianpu-hualian-ping
      newName: lianpu-hualian-ping

    - oldIndex: "2"
      newIndex: "1"
      oldName: lianpu-huadan-ping
      newName: lianpu-huadan-ping